
platform :ios,'7.0'

pod 'Masonry'
pod 'AFNetworking'
pod 'SDWebImage'
pod 'MBProgressHUD'
pod 'TTTAttributedLabel'
pod 'SSKeychain'
pod 'GPUImage'
pod 'CYLTabBarController'
pod 'iToast'
pod 'WMPageController'
pod 'MJRefresh'
pod 'AVOSCloudIM'
pod 'SBJson'
pod 'MJExtension'
pod 'Qiniu'
pod 'CRToast'
pod 'pop'
pod 'LJWKeyboardHandler'
pod 'UIActivityIndicator-for-SDWebImage'
pod 'RongCloudIMKitWithVoip'
pod 'SWTableViewCell'
pod 'JSPatch'
pod 'VEVerbalExpressions'
pod 'CTAssetsPickerController', :path => '.'